In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
file=pd.read_csv("C://Users//abhir//Downloads//csv//creditcard.csv")

In [3]:
file.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [4]:
file.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [5]:
file.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
file['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [7]:
normal=file[file.Class==0]

In [8]:
fraud=file[file.Class==1]

In [9]:
print(normal.shape)

(284315, 31)

In [10]:
print(normal.shape)

(284315, 31)

In [11]:
normal.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
file.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [14]:
normal_sample=normal.sample(n=492)

In [15]:
new_file=pd.concat([normal_sample,fraud],axis=0)

In [16]:
new_file.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
80215,58383.0,-2.473322,2.611175,-0.519941,0.938463,-0.638668,0.260759,-0.617960,1.553998,0.355294,...,-0.133186,-0.097988,-0.014142,-0.790685,0.323689,-0.136499,0.580785,0.306631,0.99,0
181981,125205.0,0.080544,0.744861,-0.029200,-0.743787,0.664837,-0.666655,0.905852,-0.067863,0.186844,...,-0.313659,-0.777095,0.008917,-0.754930,-0.451587,0.190869,0.240779,0.087267,4.99,0
60185,49199.0,-0.442287,-0.561445,2.175265,-2.364698,-1.295854,-0.598708,-0.675892,0.164465,-1.933394,...,0.054964,0.426606,-0.100246,0.330519,-0.193744,-0.238681,0.120999,0.107675,6.00,0
140324,83661.0,1.145640,-0.204698,1.309795,1.484828,-0.843832,0.542132,-0.731185,0.171877,1.332075,...,0.033491,0.612750,-0.256342,-0.024476,0.803016,-0.112545,0.099389,0.031350,14.59,0
265311,161831.0,0.849057,-1.690140,-2.524388,1.869082,-0.081688,-1.177074,1.643105,-0.677455,-0.040077,...,0.523436,0.288451,-0.634369,0.096669,0.376153,-0.455414,-0.149658,0.041723,633.40,0
136595,81778.0,0.897598,-0.428292,-0.489159,1.011975,0.617456,1.209649,0.197112,0.170292,0.059491,...,-0.049902,-0.319548,-0.451587,-1.668123,0.813431,-0.243717,0.002902,0.020527,187.67,0
206113,136073.0,0.101840,-0.576778,1.289462,-1.877632,-0.778240,-0.305432,-0.013775,-0.372703,-2.198312,...,-0.058675,0.427853,0.058156,1.162523,-0.496077,-0.127830,0.019530,-0.037734,60.00,0
163580,116062.0,2.126441,-0.859379,-1.402275,-1.027100,-0.472230,-0.879728,-0.392695,-0.277120,-0.778989,...,0.504854,1.374697,-0.102981,-0.263511,0.197683,0.070605,-0.045278,-0.070451,52.80,0
74478,55605.0,-2.642569,1.998402,0.521388,-1.875841,-1.490042,-1.207678,-0.329356,0.652307,0.225682,...,-0.132982,0.105147,-0.033361,0.705419,0.523037,-0.403833,0.653526,0.242309,0.99,0
31888,36552.0,1.157932,0.228689,0.147094,0.642261,-0.337069,-1.405980,0.546524,-0.396187,-0.318784,...,-0.322359,-1.054388,0.132508,0.733135,0.245977,0.109821,-0.069201,0.023621,59.95,0

In [17]:
new_file['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [18]:
new_file.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95486.847561,0.040258,0.027515,0.074276,-0.042116,0.004456,0.002460,0.028315,0.058906,-0.009164,...,-0.012480,-0.039433,0.005977,0.030765,-0.045573,-0.007697,-0.019751,-0.015243,0.002083,76.983110
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [19]:
X=new_file.drop(columns='Class',axis=1)

In [20]:
Y=new_file['Class']

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [22]:
model=LogisticRegression()

In [23]:
model.fit(X_train,Y_train)

LogisticRegression()

In [24]:
X_train_prediction=model.predict(X_train)

In [25]:
training_data_acuracy=accuracy_score(X_train_prediction,Y_train)*100

In [26]:
print(f"Training Data Accuracy: {training_data_acuracy}%")

Training Data Accuracy: 93.13850063532402%

In [27]:
X_test_prediction=model.predict(X_test)

In [28]:
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)*100

In [29]:
print(f"Test Data Accuracy: {test_data_accuracy}%")

Test Data Accuracy: 89.84771573604061%